version: 1
metadata:
  name: Apps - Forward auth @ Domain level
entries:
  - id: provider
    model: authentik_providers_proxy.proxyprovider
    identifiers:
      name: provider/forward-auth-domain-proxy
    attrs:
      name: Forward auth @ Domain level

      access_code_validity: minutes=30
      refresh_token_validity: days=30

      mode: forward_domain
      cookie_domain: sachathommet.fr
      authentification_url: "https://authentik.sachathommet.fr"
      external_host: "https://authentik.sachathommet.fr"
      intercept_header_auth: true
      internal_host_ssl_validation: true

      redirect_uris:
        - matching_mode: strict
          url: https://authentik.sachathommet.fr/outpost.goauthentik.io/callback?X-authentik-auth-callback=true
        - matching_mode: strict
          url: https://authentik.sachathommet.fr?X-authentik-auth-callback=true

      authorization_flow: !Find [authentik_flows.flow, [ slug, "default-provider-authorization-implicit-consent" ]]
      invalidation_flow: !Find [authentik_flows.flow, [ slug, "default-provider-invalidation-flow" ]]

      property_mappings:
        - !Find [authentik_core.propertymapping, [ name, "authentik default OAuth Mapping: OpenID 'openid'" ]]
        - !Find [authentik_core.propertymapping, [ name, "authentik default OAuth Mapping: OpenID 'profile'" ]]
        - !Find [authentik_core.propertymapping, [ name, "authentik default OAuth Mapping: OpenID 'email'" ]]

  - model: authentik_core.application
    identifiers:
      name: application/forward-auth-domain
    attrs:
      name: Forward Auth @ Domain level
      group: infra
      provider: !KeyOf provider
      policy_engine_mode: any
      slug: forward-auth-domain

  - identifiers:
      pk: !Find [ authentik_outposts.outpost, [ name, authentik Embedded Outpost ] ]
    model: authentik_outposts.outpost
    attrs:
      providers: [!KeyOf provider]
      config:
        authentik_host: "https://authentik.sachathommet.fr"
