apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gluetun-wg-private-key
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: e8430262-4590-4d80-bd79-b4b9007d5baf
