{
 "title": "Traefik logs",
 "tags": [
  "traefik",
  "loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "loki", "label": "Loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total request (2xx)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\n  {service_name=\"loki.source.kubernetes.traefik_logs\"} \n  | json \n  | DownstreamStatus >= 200 and DownstreamStatus < 300 \n  [$__range]\n))"
    }
   ]
  },
  {
   "title": "Total request (3xx)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\n  {service_name=\"loki.source.kubernetes.traefik_logs\"} \n  | json \n  | DownstreamStatus >= 300 and DownstreamStatus < 400 \n  [$__range]\n))"
    }
   ]
  },
  {
   "title": "Total request (4xx)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\n  {service_name=\"loki.source.kubernetes.traefik_logs\"} \n  | json \n  | DownstreamStatus >= 400 and DownstreamStatus < 500 \n  [$__range]\n))"
    }
   ]
  },
  {
   "title": "Total request (5xx)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\n  {service_name=\"loki.source.kubernetes.traefik_logs\"} \n  | json \n  | DownstreamStatus >= 500\n  [$__range]\n))"
    }
   ]
  },
  {
   "title": "Request volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (RequestHost) (\n  rate(\n    {service_name=\"loki.source.kubernetes.traefik_logs\"} \n    | json \n    | __error__=\"\"           # <--- This filters out the parsing errors\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"loki.source.kubernetes.traefik_logs\"} | json | DownstreamStatus >= 500"
    }
   ]
  }
 ]
}