version: 1
metadata:
  name: Sources - Google
entries:
  - id: source
    model: authentik_sources_oauth.oauthsource
    identifiers:
      name: source/google
    attrs:
      enabled: true
      name: Google
      slug: google
      provider_type: google

      access_token_url: https://oauth2.googleapis.com/token
      authorization_code_auth_method: basic_auth
      authorization_url: https://accounts.google.com/o/oauth2/v2/auth
      group_matching_mode: identifier
      user_matching_mode: identifier
      user_path_template: goauthentik.io/sources/%(slug)s

      consumer_key: !Env BLUEPRINT_SOURCES_GOOGLE_CONSUMER_KEY
      consumer_secret: !Env BLUEPRINT_SOURCES_GOOGLE_CONSUMER_SECRET

      enrollment_flow:
        !Find [
          authentik_flows.flow,
          [ slug, "default-source-enrollment" ],
        ]

      authentication_flow:
        !Find [
          authentik_flows.flow,
          [ slug, "default-source-authentication" ],
        ]

  # Bind the Google email address as a username in Authentik
  - id: expressionPolicy
    model: authentik_policies_expression.expressionpolicy
    identifiers:
      name: expressionPolicy/bind-email-to-username
    attrs:
      expression: |
        email = request.context["prompt_data"]["email"]
        request.context["prompt_data"]["username"] = email
        return False

  - id: expressionPolicyBinding
    model: authentik_policies.policybinding
    identifiers:
      order: 0
      policy: !Find [authentik_policies_expression.expressionpolicy, [name, "expressionPolicy/bind-email-to-username"]]
      target: !Find [authentik_flows.flowstagebinding, [
        stage,
        !Find [authentik_stages_prompt.promptstage, [name, "default-source-enrollment-prompt"]]
      ]]
    attrs:
      enabled: true
