apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    namespace: infra-ingress-nginx # Need to set namespace here as well, otherwise some resources are created in the wrong namespace
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    includeCRDs: true
    version: 4.13.2
    valuesInline:
      # Required by Authentik to forward auth to its Proxy Provider
      controller:
        allowSnippetAnnotations: true
        config:
          annotations-risk-level: Critical
