apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-secret
  data:
    - remoteRef:
        key: 102d954f-5108-4cfc-ab34-b358007eee3c
      secretKey: AUTHENTIK_SECRET_KEY
    - remoteRef:
        key: d4fd6937-7212-4a3a-aedc-b35800832fa3
      secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
