apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-secret
  data:
    # Used by Authentik itself
    - remoteRef:
        key: 102d954f-5108-4cfc-ab34-b358007eee3c
      secretKey: AUTHENTIK_SECRET_KEY
    - remoteRef:
        key: d4fd6937-7212-4a3a-aedc-b35800832fa3
      secretKey: AUTHENTIK_POSTGRESQL__PASSWORD

    # Used in Authentik Blueprints (YAML files in ./blueprints)
    - remoteRef:
        key: d5b27c32-fa1b-4531-af52-b35f0106519a
      secretKey: BLUEPRINT_SOURCES_GOOGLE_CONSUMER_KEY
    - remoteRef:
        key: 308e71cf-b17b-44d0-b6bb-b35f010698de
      secretKey: BLUEPRINT_SOURCES_GOOGLE_CONSUMER_SECRET

    - remoteRef:
        key: 865b5889-3188-4de8-9d27-b35f010714f1
      secretKey: BLUEPRINT_APPS_ARGOCD_CLIENT_ID
    - remoteRef:
        key: 00f34476-c47a-497d-84c3-b35f01072451
      secretKey: BLUEPRINT_APPS_ARGOCD_CLIENT_SECRET